services:
  slam:
    build:
      context: ..
      dockerfile: docker/Dockerfile.humble
    container_name: gmmslam_humble
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - gmmslam_humble_home:/root
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/workspaces/gmmslam:rw
    network_mode: host
    working_dir: /workspaces/gmmslam
    command: tail -f /dev/null

volumes:
  gmmslam_humble_home:
    name: gmmslam_humble_home
